version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12   # ✅ latest stable Python at time of writing
      docker: 20     # ✅ latest CodeBuild-supported Docker version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo No pre-build steps needed for Elastic Beanstalk deployment.
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mlproject .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
